# Generated by Django 2.2.17 on 2021-01-11 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210112_0356'),
        ('users', '0005_auto_20210112_0250'),
    ]

    operations = [
    ]
