# Generated by Django 2.2.17 on 2021-01-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingfaq',
            name='step_choice',
            field=models.CharField(choices=[('N', 'None'), ('M', 'Make'), ('B', 'Basic'), ('D', 'Detail')], default=('N', 'None'), help_text='Add step if you want to display Question in specific step', max_length=1),
        ),
    ]
