# Generated by Django 2.2.17 on 2021-01-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20210106_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingfaq',
            name='input_type',
            field=models.CharField(choices=[('S', 'Select'), ('I', 'Input'), ('T', 'Textarea'), ('C', 'Checkbox')], default=('I', 'Input'), help_text='Select type of Questions', max_length=1),
        ),
    ]
