# Generated by Django 2.2.17 on 2021-01-06 15:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20210106_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 6, 15, 47, 46, 348128, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
