# Generated by Django 2.2.17 on 2021-01-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_listing_expires_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
