# Generated by Django 2.2.17 on 2021-01-08 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_listing_is_expired'),
        ('listing', '0004_auto_20210107_1556'),
    ]

    operations = [
    ]
