# Generated by Django 2.2.17 on 2021-01-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_merge_20210108_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='expires_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
