# Generated by Django 2.2.17 on 2021-01-08 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_auto_20210108_0632'),
        ('listing', '0005_merge_20210108_0558'),
    ]

    operations = [
    ]
