# Generated by Django 2.2.17 on 2021-01-08 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_auto_20210108_0706'),
        ('listing', '0007_merge_20210108_0644'),
    ]

    operations = [
    ]
