# Generated by Django 2.2.17 on 2021-01-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_merge_20210108_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='manufacture_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
