# Generated by Django 2.2.17 on 2021-01-12 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_auto_20210110_0631'),
    ]

    operations = [
    ]
