# Generated by Django 2.2.17 on 2021-01-12 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0010_merge_20210112_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('seller_price', models.FloatField(blank=True, null=True)),
                ('buyer_percentage', models.FloatField(blank=True, null=True)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listing_type',
        ),
        migrations.AddField(
            model_name='listing',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listing.ListingPlan'),
        ),
    ]
