# Generated by Django 2.2.17 on 2021-01-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0011_auto_20210112_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
