# Generated by Django 2.2.17 on 2021-01-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0012_listingplan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingplan',
            name='listing_type',
            field=models.PositiveIntegerField(choices=[(0, 'Regular'), (1, 'No Reserve'), (2, 'Returning'), (3, 'Royalty')], default=0),
        ),
    ]
