# Generated by Django 2.2.17 on 2021-01-12 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0013_listingplan_listing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/listing_images')),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listing.Listing')),
            ],
        ),
    ]
