# Generated by Django 2.2.17 on 2021-01-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0014_listingimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
