# Generated by Django 2.2.4 on 2021-01-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0015_listing_is_approved'),
        ('listing', '0005_merge_20210107_2228'),
    ]

    operations = [
    ]
