# Generated by Django 2.2 on 2021-01-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0002_auto_20210108_2116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auction',
        ),
    ]
