# Generated by Django 2.2.17 on 2021-01-05 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.IntegerField()),
                ('bid', models.IntegerField()),
                ('status', models.PositiveIntegerField(choices=[(0, 'Failed'), (1, 'Success')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auction_buyer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auction_seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auction Detail',
                'verbose_name_plural': 'Auction Details',
                'ordering': ('created',),
            },
        ),
    ]
