# Generated by Django 2.2.17 on 2021-01-06 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listing', '0002_auto_20210106_1214'),
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidOnListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bidder', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids_on_listing', to='listing.Listing')),
            ],
            options={
                'verbose_name': 'Bid on auction',
                'verbose_name_plural': 'Bid on auctions',
                'ordering': ('created',),
            },
        ),
    ]
