# Generated by Django 2.2.17 on 2021-01-06 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_bidonlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auction.BidOnListing'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listing.Listing'),
        ),
    ]
