# Generated by Django 2.2.17 on 2021-01-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20210106_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ('-created',), 'verbose_name': 'Auction Detail', 'verbose_name_plural': 'Auction Details'},
        ),
        migrations.AlterModelOptions(
            name='bidonlisting',
            options={'ordering': ('-created',), 'verbose_name': 'Bid on auction', 'verbose_name_plural': 'Bid on auctions'},
        ),
        migrations.AddField(
            model_name='auction',
            name='buyer_amount_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='auction',
            name='seller_amount_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
