# Generated by Django 2.2.17 on 2021-01-05 00:24

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingcategory',
            options={'ordering': ('title',), 'verbose_name': 'Listing Category', 'verbose_name_plural': 'Listing Categories'},
        ),
        migrations.AlterField(
            model_name='listingcategory',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default=None, editable=False, populate_from='title', unique=True, verbose_name='Slug'),
        ),
    ]
