# Generated by Django 2.2.17 on 2021-01-07 05:15

import categories.models
import ckeditor.fields
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20210105_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingcategory',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='listingcategory',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=categories.models.list_category_image_path, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='listingcategory',
            name='image_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default=None, null=True, upload_to=categories.models.list_category_image_path),
        ),
    ]
