# Generated by Django 2.2.17 on 2021-01-07 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20210107_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingcategory',
            name='image_thumbnail',
        ),
    ]
