# Generated by Django 2.2.17 on 2021-01-07 16:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_remove_listingcategory_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingcategory',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
